### ISSUE TITLE
uproot.pandas.iterate not working in python 2 (since #332)

### ISSUE THREAD

**Issue by stderr-enst** [scikit-hep/uproot#348]
Looks like the public attributes `start` & `stop` of `RangeIndex` were only added in [pandas 0.25](https://github.com/pandas-dev/pandas/commit/873e22ef4ac1de06a3a033567daa3cc8be39ac26) which is not available for python 2.
The corresponding change in uproot was introduced in #332 .
I have a setup with pandas 0.24.2 where `uproot.pandas.iterate` throws:

```AttributeError: 'RangeIndex' object has no attribute 'start'```

because of this. Using `_start` and `_stop` is probably an easy fix?

Out of curiosity: whats the general consensus, is uproot expected to support python 2 after the its phase out in 3 months? (I should probably just migrate :))

**Comment by jpivarski** [comment]
Darn—I thought that solution would work for both the old and new Pandas. I'll put in a `hasattr` check to cover both.

In principle, we'll still support Python 2, but we won't be testing it if the tools stop making that easy. If, for instance, conda doesn't let up install Python 2 anyone, we'll have to take it out of continuous integration. (This is the same situation we're in for Python 2.6. I still write 2.6-compliant idioms, though we don't have an easy way to test the code against 2.6.)

**Comment by jpivarski** [comment]
Let me know if PR #351 works for you. I plan to include it in uproot version [3.10.2](https://github.com/scikit-hep/uproot/releases/tag/3.10.2).
