### ISSUE TITLE
Install error for Python 3.7

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot#192]
I tried to install uproot for Python3.7 on my Mac. It works for Python 2, but not for Python3, which are both installed. Python2 is the default interpreter. I get the following error:
```
python3 -m pip install --user uproot
Collecting uproot
  Using cached https://files.pythonhosted.org/packages/a9/f0/ffd47865b5fb2693c78d5067343ea3fe1933b3042cc1e3380c2498c4bb7c/uproot-3.2.14-py2.py3-none-any.whl
Collecting cachetools (from uproot)
  Using cached https://files.pythonhosted.org/packages/76/7e/08cd3846bebeabb6b1cfc4af8aae649d90249b4aeed080bddb5297f1d73b/cachetools-3.0.0-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.13.1 in ./Library/Python/3.7/lib/python/site-packages (from uproot) (1.15.4)
Collecting lz4 (from uproot)
  Using cached https://files.pythonhosted.org/packages/f1/4f/878f1827042c5b6828bc23d160f31e242ec820810b8bd04b30b631029952/lz4-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zv/g5pxjgwj4xs8x598864qzdgw0000gn/T/pip-install-t8wvdwkh/lz4/setup.py", line 34, in <module>
        liblz4_found = pkgconfig_installed('liblz4', LZ4_REQUIRED_VERSION, default=False)
      File "/private/var/folders/zv/g5pxjgwj4xs8x598864qzdgw0000gn/T/pip-install-t8wvdwkh/lz4/setup.py", line 24, in pkgconfig_installed
        installed = pkgconfig.installed(lib, required_version)
    AttributeError: module 'pkgconfig' has no attribute 'installed'
```

**Comment by HDembinski** [comment]
I successfully installed numpy and scipy in the same way, so I think this is uproot-specific.

**Comment by chrisburr** [comment]
I think this is a bug in the `setup.py` of `lz4`. I think you can work around it by running this before installing uproot:

```bash
python3 -m pip install --user pkgconfig
```

**Comment by HDembinski** [comment]
Thanks, this works! Can this be fixed by adding pkgconfig to the install requirements?

**Comment by chrisburr** [comment]
Probably, though I'm now having difficulty reproducing the bug to check.

**Comment by jpivarski** [comment]
I'll try it out on an AWS VM with and without pkgconfig. If it's necessary, I'll add it to the dependencies. The timing is perfect: I'm working on a version 3.3.0 today to change the dependencies set (to require upstream changes in awkward).

**Comment by jpivarski** [comment]
Actually, I couldn't reproduce the installation error in AWS (Ubuntu Linux); it must be a Mac thing. I did, however, hit the issue that if gcc isn't installed, lz4 can't be. The lz4 package for Windows is precompiled binaries; is it on Mac as well? Do Macs typically have gcc installed? (Linux usually does, but a freshly minted server doesn't.)

Perhaps we should revive the uproot in conda idea. It could break down like this:

   * uproot in pip depends on numpy, awkward, uproot-methods, and cachetools; users get a how-to message when they want to open an lz4-compressed file or an lzma-compressed file in Python 2.
   * uproot in conda depends on numpy, awkward, uproot-methods, cachetools, pyxrootd, lz4, and (in Python 2), backports.lzma.

This way, only the conda version depends on any compiled extensions other than Numpy. The pyxrootd dependency would be particularly hard to satisfy without conda. In issue #190, however, I'm hearing from @PerilousApricot that an XRootD client might not even be necessary— that we can access XRootD as though it were HTTP(S). (uproot chunks them both the same way, anyway.)

**Comment by jpivarski** [comment]
In the next big version of uproot, 0.3.0, lz4 will be an optional dependency when installing from pip. It goes against the spirit of uproot to require gcc. Users will get a how-to message if they don't have lz4 and need it (as they did in uproot 2).

I'd still like to get a conda version going with all dependencies in, but that's coupled with getting a scikit-hep conda channel.

**Comment by chrisburr** [comment]
> The lz4 package for Windows is precompiled binaries; is it on Mac as well? Do Macs typically have gcc installed?

It compiles on install. Macs have clang either by default or after running `xcode-select --install` which everybody who might use uproot will have already done.

> Shipping uproot as a conda package

I think this is a good idea though my only concern would be with how to do the deployments. Having a specific channel isn't great as managing them quickly becomes difficult. Using `conda-forge` gets around this, but then deploying a new version means making a PR to the "uproot-feedstock" repository which then has to be merged by one of the maintainers. The maintainers are managed on a per package basis so this could still be done by you, or possibly even triggered by uproot's CI using the GitHub API.

> an XRootD client might not even be necessary

For the XRootD server's that I interact with (as part of LHCb) the HTTP plugin isn't enabled so I suspect there will always be a need to access data using XRootD. That said, I think reading files via HTTP using `requests` would be useful.

**Comment by jpivarski** [comment]
Okay, good to know about HTTP. We can't assume that it's on.

I don't know enough about the trade-offs in deploying by conda. Do you think it's feasible given our people-power? Hans is rapidly demonstrating my inability to keep up with package maintenance: the Travis-deploy has been a major enabler for me. I was thinking of a Scikit-HEP channel because there are other things we want to deploy, like root_numpy, ROOT itself, XRootD... I'm getting the impression here that it's a lot more work than PyPI.

**Comment by eduardo-rodrigues** [comment]
Hi folks, from discussions @henryiii and I had, we both like the idea of the conda channel. This seems a perfect conversation for the admins mailing list, to converge asap :-).

**Comment by henryiii** [comment]
PS: There already is a channel in conda, "hep". Though conda-forge would be much simpler and better in terms of people power. Since Uproot is only using it for dependencies, it would be borderline trivial to add.

**Comment by henryiii** [comment]
If someone had time, I think there's at least a little interest in fixing it from LZ4's side, which would be best: https://github.com/python-lz4/python-lz4/issues/99

**Comment by jpivarski** [comment]
I didn't know the conda channel "hep" existed, but if there's momentum there, that sounds like it would be good to join. I'm going to start the Scikit-HEP admins email discussion, because that's where it belongs.

**Comment by chrisburr** [comment]
I'm drafting out an email at the moment to get the discussion started there.

**Comment by jpivarski** [comment]
Oh, then I won't. I'll discard my one sentence now. (Everybody here is so fast!)

References to this issue and the PR where this has been talked about: `https://github.com/scikit-hep/uproot/pull/183` and `https://github.com/scikit-hep/uproot/issues/192`.

**Comment by raymondEhlers** [comment]
Just FYI (even though it appears that you've worked around the `pkgconfig` issue):

The `pkgconfig` issue appears to be related to ROOT (at least when I experienced it). In particular, at least some build configurations appear to create an empty `pkgconfig` directory in the `$ROOTSYS/lib` directory, which python3 then sees as an empty `pkgconfig` package. I worked out [a different approach](https://github.com/python-lz4/python-lz4/pull/160) with the `python-lz4` developers, and they just tagged it. So some of the underlying problems should be resolved.

I also [reported the ROOT issue](https://sft.its.cern.ch/jira/browse/ROOT-9864), but we haven't sorted out the cause yet.
